apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: todo
    tier: backend
type: Opaque
data:
# base64 encoded values
  SPRING_DATASOURCE_USERNAME: dmlzaGFs # echo -n 'vishal' | base64
  SPRING_DATASOURCE_PASSWORD: ZHdpdmVkaQ== # echo -n 'dwivedi' | base64
  COHERE_API_KEY: Y29oZXJlLWR1bW15LWtleS0xMjM0NQ==
  SLACK_WEBHOOK: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vZHVtbXkvd2ViaG9vay8xMjM0NQ==